CREATE TABLE USUARIOS (
    ID INT NOT NULL PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    SENHA VARCHAR2(255) NOT NULL,
    TELEFONE VARCHAR2(20),
    ENDERECO VARCHAR(50),
    PERFIL VARCHAR2(20) CHECK (PERFIL IN ('CLIENTE', 'GERENTE')) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'BLOQUEADO' CHECK (STATUS IN ('ATIVO', 'INATIVO', 'BLOQUEADO')),
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CONTAS (
    ID INT NOT NULL PRIMARY KEY,
    AGENCIA INT NOT NULL,
    NUMERO_CONTA INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    SALDO NUMBER(15,2) DEFAULT 0.00,
    TIPO VARCHAR2(20) CHECK (TIPO IN ('CORRENTE', 'POUPANCA')) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'BLOQUEADO' CHECK (STATUS IN ('ATIVA', 'BLOQUEADA')),
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CONTAS_USUARIOS FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
);


CREATE TABLE MOVIMENTACOES (
    ID INT NOT NULL PRIMARY KEY,
    CONTA_ORIGEM_ID INT,
    CONTA_DESTINO_ID INT,
    VALOR NUMBER(15,2) NOT NULL,
    TIPO VARCHAR2(30) CHECK (TIPO IN ('DEPOSITO', 'TRANSFERENCIA', 'INVESTIMENTO', 'SAQUE')),
    DATA_TRANSACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP, /* Melhorar representação do banco com base na transação, acrescentando data de início e fim do processo */
    DESCRICAO VARCHAR(200),
    STATUS VARCHAR2(20) DEFAULT 'PENDENTE' CHECK (STATUS IN ('PENDENTE', 'CONCLUIDA', 'FALHA')),
    CONSTRAINT FK_MOV_CONTA_ORIGEM FOREIGN KEY (CONTA_ORIGEM_ID) REFERENCES CONTAS(ID),
    CONSTRAINT FK_MOV_CONTA_DESTINO FOREIGN KEY (CONTA_DESTINO_ID) REFERENCES CONTAS(ID)
);



CREATE TABLE INVESTIMENTOS (
    ID INT NOT NULL PRIMARY KEY,
    CONTA_ID INT NOT NULL,
    TIPO_INVESTIMENTO VARCHAR2(100) NOT NULL,
    VALOR_INVESTIDO NUMBER(15,2) NOT NULL,
    DATA_INICIO DATE DEFAULT SYSDATE,
    DATA_FIM DATE,
    STATUS VARCHAR2(20) DEFAULT 'ATIVO' CHECK (STATUS IN ('ATIVO', 'ENCERRADO')),
    CONSTRAINT FK_INVEST_CONTA FOREIGN KEY (CONTA_ID) REFERENCES CONTAS(ID)
);


CREATE TABLE EMPRESTIMOS (
    ID INT NOT NULL PRIMARY KEY,
    CONTA_ID INT NOT NULL,
    VALOR_EMPRESTIMO NUMBER(10,2) NOT NULL,
    JUROS NUMBER(10,2) NOT NULL,
    PARCELAS INT NOT NULL,
    STATUS VARCHAR2(30) DEFAULT 'SIMULADO' CHECK (STATUS IN ('SIMULADO', 'APROVADO', 'EM_ANDAMENTO', 'QUITADO')),
    DATA_SOLICITACAO DATE DEFAULT SYSDATE,
    DATA_APROVACAO DATE,
    DATA_ULTIMO_PAGAMENTO DATE,
    CONSTRAINT FK_EMPRESTIMO_CONTA FOREIGN KEY (CONTA_ID) REFERENCES CONTAS(ID)
);



   


--sequences

CREATE SEQUENCE SEQ_USUARIOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE SEQUENCE SEQ_CONTAS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE SEQUENCE SEQ_MOVIMENTACOES
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE SEQUENCE SEQ_INVESTIMENTOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE SEQUENCE SEQ_EMPRESTIMOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;




CREATE SEQUENCE SEQ_NUM_CONTA
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


INSERT INTO USUARIOS (
    ID,
    NOME,
    EMAIL,
    SENHA,
    TELEFONE,
    ENDERECO,
    PERFIL,
    STATUS,
    DATA_CRIACAO,
    DATA_ULTIMA_ATUALIZACAO
) VALUES (
    SEQ_USUARIOS.NEXTVAL,
    'Miguel Baptista',
    'miguel.baptista@email.com',
    'SenhaSegura123'
    '(11) 98765-4321',
    'Rua Exemplo, 123, São Paulo, SP',
    'CLIENTE',
    'ATIVO',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

 