BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE INVESTIMENTOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EMPRESTIMOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MOVIMENTACOES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CONTAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USUARIOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIOS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONTAS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MOVIMENTACOES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_INVESTIMENTOS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPRESTIMOS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NUM_CONTA';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE USUARIOS (
    ID INT NOT NULL PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    SENHA VARCHAR2(255) NOT NULL,
    TELEFONE VARCHAR2(20),
    ENDERECO VARCHAR(50),
    PERFIL VARCHAR2(20) DEFAULT 'CLIENTE' CHECK (PERFIL IN ('CLIENTE', 'GERENTE')),
    STATUS VARCHAR2(20) DEFAULT 'BLOQUEADO' CHECK (STATUS IN ('ATIVO', 'INATIVO', 'BLOQUEADO')),
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CONTAS (
    ID INT NOT NULL PRIMARY KEY,
    AGENCIA INT NOT NULL,
    NUMERO_CONTA INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    SALDO NUMBER(15,2) DEFAULT 0.00,
    TIPO VARCHAR2(20) CHECK (TIPO IN ('CORRENTE', 'POUPANCA')) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'BLOQUEADO' CHECK (STATUS IN ('ATIVA', 'BLOQUEADA')),
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CONTAS_USUARIOS FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE MOVIMENTACOES (
    ID INT NOT NULL PRIMARY KEY,
    CONTA_ORIGEM_ID INT,
    CONTA_DESTINO_ID INT,
    VALOR NUMBER(15,2) NOT NULL,
    TIPO VARCHAR2(30) CHECK (TIPO IN ('DEPOSITO', 'TRANSFERENCIA', 'INVESTIMENTO', 'SAQUE')),
    DATA_TRANSACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DESCRICAO VARCHAR(200),
    STATUS VARCHAR2(20) DEFAULT 'PENDENTE' CHECK (STATUS IN ('PENDENTE', 'CONCLUIDA', 'FALHA')),
    CONSTRAINT FK_MOV_CONTA_ORIGEM FOREIGN KEY (CONTA_ORIGEM_ID) REFERENCES CONTAS(ID),
    CONSTRAINT FK_MOV_CONTA_DESTINO FOREIGN KEY (CONTA_DESTINO_ID) REFERENCES CONTAS(ID)
);

CREATE TABLE INVESTIMENTOS (
    ID INT NOT NULL PRIMARY KEY,
    CONTA_ID INT NOT NULL,
    TIPO_INVESTIMENTO VARCHAR2(100) NOT NULL,
    VALOR_INVESTIDO NUMBER(15,2) NOT NULL,
    DATA_INICIO DATE DEFAULT SYSDATE,
    DATA_FIM DATE,
    STATUS VARCHAR2(20) DEFAULT 'ATIVO' CHECK (STATUS IN ('ATIVO', 'ENCERRADO')),
    CONSTRAINT FK_INVEST_CONTA FOREIGN KEY (CONTA_ID) REFERENCES CONTAS(ID)
);

CREATE TABLE EMPRESTIMOS (
    ID INT NOT NULL PRIMARY KEY,
    CONTA_ID INT NOT NULL,
    VALOR_EMPRESTIMO NUMBER(10,2) NOT NULL,
    JUROS NUMBER(10,2) NOT NULL,
    PARCELAS INT NOT NULL,
    STATUS VARCHAR2(30) DEFAULT 'SIMULADO' CHECK (STATUS IN ('SIMULADO', 'APROVADO', 'EM_ANDAMENTO', 'QUITADO')),
    DATA_SOLICITACAO DATE DEFAULT SYSDATE,
    DATA_APROVACAO DATE,
    DATA_ULTIMO_PAGAMENTO DATE,
    CONSTRAINT FK_EMPRESTIMO_CONTA FOREIGN KEY (CONTA_ID) REFERENCES CONTAS(ID)
);

CREATE SEQUENCE SEQ_USUARIOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CONTAS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MOVIMENTACOES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INVESTIMENTOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMPRESTIMOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NUM_CONTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

INSERT INTO USUARIOS (
    ID,
    NOME,
    EMAIL,
    SENHA,
    TELEFONE,
    ENDERECO,
    PERFIL,
    STATUS,
    DATA_CRIACAO,
    DATA_ULTIMA_ATUALIZACAO
) VALUES (
    SEQ_USUARIOS.NEXTVAL,
    'Miguel Batista',
    'miguel.batista@gerente.com',
    'SenhaSegura123',
    '(11) 98765-4321',
    'Rua Exemplo, 123, São Paulo, SP',
    'GERENTE',
    'ATIVO',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

INSERT INTO CONTAS (
    ID,
    AGENCIA,
    NUMERO_CONTA,
    USUARIO_ID,
    SALDO,
    TIPO,
    STATUS,
    DATA_CRIACAO
) VALUES (
    SEQ_CONTAS.NEXTVAL,
    0001,
    SEQ_NUM_CONTA.NEXTVAL,
    (SELECT ID FROM USUARIOS WHERE EMAIL = 'miguel.batista@gerente.com'),
    5000.00,
    'CORRENTE',
    'ATIVA',
    CURRENT_TIMESTAMP
);

commit;
